name: Release Windows Binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Compile for Windows
      run: deno compile --target=x86_64-pc-windows-msvc -A --output local-dicomweb.exe main.mjs

    - name: Upload binary to release
      uses: softprops/action-gh-release@v1
      with:
        files: local-dicomweb.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
